language: node_js
node_js:
- '0.12'
sudo: false
cache:
  directories:
  - node_modules
env:
  matrix:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  global:
  - GITHUB_USER=tomster-strudel
  - secure: ZuEENBDKyFtqjp7em/ajkoj+CMOwtMCp20vv7de+jguGvQwDbrKRcQZ+Ai87bGTjoyolXFlXtFFb+4aqiqY1JeNj8HA+OTLVaad0WxxSbW/+Oz/1UPoMkbqkfdepqH3lXjo2lCnJbDUa5aI8Em0W0Iuq1YX3iSEzi+b1Bi4A8ZM50nIgTIQxHeMKBvAKBuz0QUhpEhFFbdlD0BMUD+fbUaaBQ2kxiXGISGCRohkaqhDD68wQhVYdlNBn+Z2yp/YM0+kUZp9FqX8XA47vJkVKBLPydMp0x9GhOfF2FPnqksl0M1LTiuvMTNazOwXkNSoLV8aQxS8GCtVi3RhpEkK8KUF/+rX0AG6TZPQTaQ+yVaXb2+7UqpyUs630TZGIe2nFfWeBCYw/Hw+hjD9EQhCc8r6CinCGYd2diiszGDRQYItM5VZDuBwQu0WxDVOj+BDRFFHoYn7am3hFhX2ERsHllBpXN5eZZC1peVwHIsCRsHIiyC77vxQl+BBqAljUHoAg5TEB+K9exCnp4G73eImDwJvBrPuLpKVWT6Zxh7N8ItXUHM/lX0VWor8fbILGSQ2v3YEzzrITDHmEBoc89lAms6Bkva+tw/OpM6ZPPi/Xmxm+otsTNHKOEw5G+tTnUIetRSqWHjSv7Q0PN2v7MLcVuUSL8bedIRmyz9jeCmzlTX0=
  - secure: YswqcRblayqN/yKzlGJtHxLTrdQyGduEaRIyIQp4FLXeXR0NgZ/dgcmKyi00aqeyCUXSkRoXHuYp8D9sY7eYNw6qOquhOQLXD+1oyUUVPPfObiKtMamuzjRKl2sYCkfNdvAcIKLbuyA9Si7GWRj5w2JHjm3Go0mHGcoUftvl7K92TJsNW650T4gymFM0/9rJOD7Rx8+Vyq7xsQ+Se48ZuEaNDgxYua/7RmjRmWYClSRhTEpoiEA1OB8VAt4zxRUJ1Glj1w6NFLxSKgCrk8tgerVB2+Er50D/CrYZ+EtBWK8XLDSMq96hXeENbsQS0f6SG4yGgzyJRrBZiwtdY1cRU33nPZr7kScQtlDe7zoPTl0p03gy3f7b23YrryftxQeTzCMDgFCDaIS37kc05IAMzZafOJBNY+qp8/jUYcgVaeB4bqngLsLQiw3dU+r0R4PTHHCvqYOsqgc1FEL23X6bSdJEgZqYH6ITMlMZSxF3Iy/oG6484e0bQHdOLsISv3WS05MAZD/hLUfv/9qSrW0wmRRP8tiUe4CCO6N7ys18covYPHyGK1LDeJ+FM3fmDCt5ZEb1NLjih4OS5cogBSrj9I/QzZs/m0W31bn55+9Bqtwx22u0S4wg/VbSLLtYoTsas4L89OC+gmoCD45b0VfaNYRXjDH1U+HQiawW6iMkY1U=
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
- export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
- npm config set spin false
- npm install -g npm@^2
install:
- npm install -g bower
- npm install
- bower install
script:
- ember try $EMBER_TRY_SCENARIO test
after_success:
- ember try:reset
- ember build --environment=production
- bin/release
- rm -rf active-model-adapter-dist
before_deploy:
- '[[ -d "./dist" ]] || ember build --environment=production'
deploy:
- provider: rubygems
  gemspec: active-model-adapter-source.gemspec
  on:
    tags: true
  api_key:
    secure: X7734CGXXQMAtjScj5Vs+T4G+Axa5FzROKGQM2sP255TUiCnGe3SzPJHmzrkrE/XNSs62tmeHAKCt/dEqJVOpM46Ain9aI+/ETuadMF/ihnS4VnYqzN1+MvhbAvxB++xfb/f+Zw/n7kotH7fIsGdUsaLBiClli/J8/kojh7ueoEVFrUEZIhZ6zl8jCNSGxP7MlQ+IDBXOlNpyRpxnkiPTXUxcoFJjk9lu3+AcX16nU06p4+uscmnboGKZr0cSooRmWBiSRS7GIYBl38bkI8JE20ZCrLe8JdbSgWoA4jpRSgEL6ZuDv7QcOk02pPjii1iEK41gMQgmcun3BEfd3TuJpQPaEv23XCjpCp1xFpG5hKVEXimSjsYFab7Qr8DOLoW3goeoxzZrbbsY1cVEwcMXE2j8433i6dizateQNAwMMTpWQLoRtj83YMxmLcZbouGjTLJavli5Flyin0+lfXXIz/UQb0Hp9xeb70DWRYY6xttApAgay86SBtF3HbTqUMD2I8iEZyqCIEIqzdD10LrL0ZpYu86pFHqj1mrlLXbR78sKcFrwfc02DiQmsDRcVmpwHa2RcpWFIXpa2U2fcmkXuEK7dGdV5MoNujFergbv4KqMW+16ny5FKsCt/G/40obCPNTW7m+7Bww9N3tyD2OJgvWn2/54IT6ONzVwDJH/QQ=
- provider: npm
  email: stanley+ember-data@stan.li
  on:
    tags: true
  api_key:
    secure: "lTlchYEhxcyvGdl47pxaQ8z0zjDPtq6ccyPvDVnjkuYCdFCC9iNIwFeKvozpiRoQBis9zauOEfk2ny7MVDi7bIxC5WMkWFHM1kxdYKaMdT82VUvEaKSjSblnhd2MJ9s1Ueb7Nw6GyXiw52ytB+CHYjSLoCPucPZwSXOv9RVNdvmF+ydnCZt5xapMr5T2uInKMDaT/wrYhdpzEdggFvZnzzo5WTeLMsjxMeWx922cYIdosM7R3X8DEfHfiqcgviere6ntd9ikWX8M3ycnpF/5zfyvAsUWgfaLi0acmrEP0Pqh69lMP+40Qj2wSfHQIhUeEC0mIg1T3Eo+2tNXvcW2yQYwDot20AraSj8zDVNvA0ByLIS14do/P73VNd32/3dF0qiy0fgk1UBGyuL6ZWX+LzjGlgl8iY9zSB2ruPgs0GQnr8GFhXy+FYze9F5K8+XtoYSt245Dy5N0A4PV9TdQgd8/HJ+dI1a9nPOx6Y0kWCv85txeet18/sbzx4DG2ENcwE+n8npxaa+ipxWNs1XxLP28Dxr+dptUgBq5yM07Mq84qKPYPqpsRw+kTTp8gkjm380RZ7QZojCCB0gsaKArSN+6EZ/WAUII2dpl/VvLDzz2nO49oODr5zd8Lp3oMpqtrgTl+f54ZDODXLbmalNNWZgMpPj/STsMqDV5OnkcefI="
  clean_up: false
